In [1]:
import numpy as np

In [ ]:
# element wise operations (each element gets multipled twice and maintains its structure)

In [7]:
# scenarios

# we want to know the labour cost for fixing my car

# labour cost = labour hours x cost per hour

In [52]:
# Labour hours

#col = oil change, tune up, repairs
#rows = compact, suv, van
hours = np.array([[1,2,5],[2,4,10],[4,8,20]])
hours

array([[ 1,  2,  5],
       [ 2,  4, 10],
       [ 4,  8, 20]])

In [63]:
# cost per hour at two different shopers

#col = oil change, tune up, repairs
# rows = honda shop vs local mechanic
cost = np.array([[25,50,45],[20,60,40]])
cost

array([[25, 50, 45],
       [20, 60, 40]])

In [65]:
# cost at honda shop
hours * cost[0,:]

array([[ 25, 100, 225],
       [ 50, 200, 450],
       [100, 400, 900]])

In [66]:
# cost at local mechanic
hours * cost[1,:]

array([[ 20, 120, 200],
       [ 40, 240, 400],
       [ 80, 480, 800]])